version: "3.9"

services:
  server:
    user: root 
    image: registry.netaster.com/halitsever/advanced-telegram-economy:1.0.0
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - LANG=${LANG}
    volumes:
      - /data-telegram-bot:/app/data.sqlite:rw
    restart: always